# Make mehrere Programme, die im Rahmen des Praktikum 08 in SysProg
# erstellt wurden
all: childWait childWaitpid starter

# Programm Praktikum 08 Aufgabe 1
childWait: pr08-1.c
	gcc -g -Wall -o childWait pr08-1.c

# Programm Praktikum 08 Aufgabe 2
childWaitpid: pr08-2.c
	gcc -g -Wall -o childWaitpid pr08-2.c

# Programm Praktikum 08 Aufgabe 3
starter: starter.c
	gcc -g -Wall -o starter starter.c
